# Agent Task Routing Rules
#
# Defines rules for routing tasks to appropriate agents based on task type,
# file patterns, and context. Used by meta-agents to determine agent selection.
#
# Version: 1.0.0
# Last Updated: 2026-02-10
# Access: Protected - Meta-intelligence layer only

# Primary Routing Rules
routing_rules:
  # Code-related tasks
  - pattern: "**/*.scss"
    context: "legacy CSS conversion"
    route_to: scss-refactor-agent
    priority: high
    validation_required: true
    follow_up:
      - responsive-design-agent
      - futuristic-effects-agent

  - pattern: "**/*.scss"
    context: "responsive design implementation"
    route_to: responsive-design-agent
    priority: high
    validation_required: true
    dependencies:
      - theme-genome-agent  # Ensure ontology is available

  - pattern: "**/*.scss"
    context: "visual effects enhancement"
    route_to: futuristic-effects-agent
    priority: medium
    validation_required: true
    dependencies:
      - responsive-design-agent  # Effects after responsive

  - pattern: "**/*.{html,liquid}"
    context: "semantic HTML creation"
    route_to: html-template-agent
    priority: high
    validation_required: true
    follow_up:
      - scss-refactor-agent  # Apply styling

  - pattern: "_layouts/**/*.html"
    context: "Jekyll layout updates"
    route_to: html-template-agent
    priority: critical
    validation_required: true
    notes: "Theme layouts affect all subdomains"

  - pattern: "_includes/**/*.html"
    context: "Jekyll include components"
    route_to: html-template-agent
    priority: high
    validation_required: true

  # Ontological tasks
  - pattern: "_sass/ontology/**"
    context: "engine layer changes"
    route_to: theme-genome-agent
    priority: critical
    validation_required: true
    approval_required: true
    notes: "All engine changes must be reviewed"

  - pattern: "GENOME.md"
    context: "evolutionary history update"
    route_to: theme-genome-agent
    priority: high
    validation_required: true

  - pattern: "ontological-proposition"
    context: "new variant proposal"
    route_to: theme-genome-agent
    priority: critical
    validation_required: true
    approval_required: true
    source: subdomain-evolution-agent

  # Documentation tasks
  - pattern: "docs/**/*.md"
    context: "documentation updates"
    route_to: documentation-manager-agent
    priority: medium
    validation_required: true

  - pattern: "**/*.md"
    context: "documentation validation"
    route_to: documentation-manager-agent
    priority: low
    validation_required: false
    notes: "Pre-commit validation"

  - pattern: ".github/**/*.md"
    context: "agent documentation"
    route_to: documentation-manager-agent
    priority: medium
    validation_required: true
    follow_up:
      - agent-evolution-agent  # Update metrics

  # Meta-intelligence tasks
  - pattern: ".github/**"
    context: "agent quality audit"
    route_to: agent-evolution-agent
    priority: high
    validation_required: false
    notes: "Self-improvement workflow"

  - pattern: ".github/prompts/**"
    context: "agent prompt optimization"
    route_to: agent-evolution-agent
    priority: medium
    validation_required: true

  - pattern: ".github/skills/**"
    context: "skill quality improvement"
    route_to: agent-evolution-agent
    priority: medium
    validation_required: true

# Task Type Routing
task_types:
  new_feature_development:
    sequence:
      - agent: html-template-agent
        task: Create semantic HTML structure
      - agent: scss-refactor-agent
        task: Map to ontological mixins
      - agent: responsive-design-agent
        task: Ensure mobile-first patterns
      - agent: futuristic-effects-agent
        task: Add visual effects
      - agent: subdomain-evolution-agent
        task: Identify gaps (if any)
        conditional: true

  legacy_migration:
    sequence:
      - agent: html-template-agent
        task: Audit and refactor HTML
      - agent: scss-refactor-agent
        task: Convert to zero-CSS ontology
      - agent: responsive-design-agent
        task: Add responsive enhancements
      - agent: futuristic-effects-agent
        task: Modernize effects

  ontological_evolution:
    sequence:
      - agent: subdomain-evolution-agent
        task: Identify and propose gap
      - agent: theme-genome-agent
        task: Review and approve/reject
      - agent: theme-genome-agent
        task: Implement in engine (if approved)
        conditional: true
      - agent: scss-refactor-agent
        task: Adopt new variants
        conditional: true

  accessibility_audit:
    parallel:
      - agent: html-template-agent
        task: WCAG compliance check
      - agent: responsive-design-agent
        task: Touch targets and typography
    sequence:
      - agent: scss-refactor-agent
        task: Ensure semantic purity maintained

  documentation_quality:
    parallel:
      - agent: documentation-manager-agent
        tasks:
          - Validate structure
          - Check links
          - Detect redundancy
          - Validate metadata

  agent_self_improvement:
    sequence:
      - agent: agent-evolution-agent
        task: Audit quality metrics
      - agent: agent-evolution-agent
        task: Track metrics over time
      - agent: agent-evolution-agent
        task: Detect duplication
      - agent: agent-evolution-agent
        task: Recommend improvements
      - agent: agent-evolution-agent
        task: Sync with specifications

# Context-Based Routing
context_routing:
  keywords:
    # SCSS-related
    - patterns: ["mixin", "ontology", "zero-css", "semantic SCSS"]
      route_to: scss-refactor-agent
    
    - patterns: ["responsive", "mobile-first", "breakpoint", "touch target"]
      route_to: responsive-design-agent
    
    - patterns: ["glassmorphism", "neon", "quantum", "visual effect"]
      route_to: futuristic-effects-agent
    
    # HTML-related
    - patterns: ["semantic HTML", "accessibility", "WCAG", "landmark", "ARIA"]
      route_to: html-template-agent
    
    # Ontological
    - patterns: ["ontological proposition", "variant", "engine layer", "GENOME"]
      route_to: theme-genome-agent
    
    - patterns: ["semantic gap", "missing pattern", "propose variant"]
      route_to: subdomain-evolution-agent
    
    # Documentation
    - patterns: ["documentation", "update docs", "broken link", "redundant"]
      route_to: documentation-manager-agent
    
    # Meta
    - patterns: ["agent quality", "spec coverage", "duplication", "metrics"]
      route_to: agent-evolution-agent

# Priority Levels
priority_definitions:
  critical:
    response_time: immediate
    requires_approval: true
    examples:
      - Engine layer changes
      - Theme layout modifications
      - Ontological propositions

  high:
    response_time: priority
    requires_approval: false
    examples:
      - New feature SCSS
      - Semantic HTML creation
      - Responsive implementation

  medium:
    response_time: normal
    requires_approval: false
    examples:
      - Visual effects
      - Documentation updates
      - Agent improvements

  low:
    response_time: batch
    requires_approval: false
    examples:
      - Documentation validation
      - Metrics tracking
      - Quality audits

# Validation Requirements
validation:
  always_required:
    - scss-refactor-agent
    - html-template-agent
    - responsive-design-agent
    - theme-genome-agent

  optional:
    - futuristic-effects-agent
    - documentation-manager-agent

  never_required:
    - agent-evolution-agent  # Meta-agent doesn't need external validation

# Conflict Resolution
conflict_resolution:
  # If multiple agents could handle a task
  - scenario: "SCSS file needs both refactoring and responsive work"
    resolution:
      sequence:
        - scss-refactor-agent  # Refactor first
        - responsive-design-agent  # Then responsive
    
  - scenario: "HTML needs both semantic structure and styling"
    resolution:
      sequence:
        - html-template-agent  # Structure first
        - scss-refactor-agent  # Styling second
    
  - scenario: "Documentation and code both need updates"
    resolution:
      parallel:
        - Primary agent for code
        - documentation-manager-agent for docs

# Emergency Overrides
emergency_protocols:
  security_vulnerability:
    route_to: theme-genome-agent
    priority: critical
    bypass_normal_routing: true
    requires_immediate_action: true

  breaking_change:
    route_to: theme-genome-agent
    priority: critical
    requires_approval: true
    notification_required: true

  accessibility_violation:
    route_to: html-template-agent
    priority: critical
    validation_required: true
    must_fix_before_merge: true
